### ISSUE TITLE
Results reporting

### ISSUE THREAD

**Issue by fenhl** [smashgg/developer-portal#185]
An API endpoint (e.g. GraphQL mutation) for submitting match results would be very useful to have.

**Comment by jbkennaugh** [comment]
Second this! I have some ideas for passion projects that I could work on that involve inputting a score, inputting stage data, character data etc. and it'd be hugely appreciated if you could do this with a mutation :)

**Comment by keithrobichaud** [comment]
Reporting match results is now available :)
