### ISSUE TITLE
Force redirect `dev.start.gg/*` to `developer.start.gg/*`

### ISSUE THREAD

**Issue by tobybaratta** [smashgg/developer-portal#187]
Right now, if you go to `dev.start.gg`, it resolves properly - however, all URLs from that main page are are relative to the basic `dev` subdomain, and then none of those sites and URLs actually load.

Fix: 
1. Make `dev.start.gg` force redirect to `developer.start.gg`. Make all direct URLs to `dev.start.gg` endpoints automatically redirect properly to the `developer.start.gg` URLs. IE: If I go to `dev.start.gg/explorer`, it returns a 308 (Permanent Redirect) to `developer.start.gg/explorer`.
2. Make `dev.start.gg` mirror *all* of `developer.start.gg`, so that URLs off the domain actually work.

**Comment by nathanwelch** [comment]
Hey @tobybaratta do you have a specific link that breaks when doing this? I can't repro. Everything on dev.start.gg seems to work but I might be missing it

**Comment by tobybaratta** [comment]
I mean, the dev site sometimes is just ded (Discord folk agree) -- screenshot here:
<img width="1200" alt="image" src="https://github.com/smashgg/developer-portal/assets/6365705/d11b1107-707b-4f1f-af1e-b60435b1f91f">

Seems like right now the site isn't dead, it just takes a really long time to load any page if they load at all, the theming is broken, but does eventually pages are loading.

**Comment by nathanwelch** [comment]
Those sound like completely different issues than the original so i'm going to close this and we'll look into those. Thanks!
